//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LexlyDemo {
    using System.Collections.Generic;
    
    internal partial class SlangTokenizer : Tokenizer {
        internal static int[][] Program = new int[][] {
                new int[] {
                        10,
                        0},
                new int[] {
                        2,
                        2,
                        9,
                        19,
                        26,
                        36,
                        45,
                        53,
                        63,
                        74,
                        83,
                        91,
                        98,
                        103,
                        108,
                        119,
                        127,
                        133,
                        140,
                        149,
                        155,
                        165,
                        169,
                        176,
                        187,
                        190,
                        195,
                        198,
                        207,
                        214,
                        219,
                        227,
                        234,
                        241,
                        246,
                        252,
                        258,
                        262,
                        266,
                        269,
                        273,
                        276,
                        279,
                        282,
                        285,
                        288,
                        291,
                        294,
                        297,
                        300,
                        304,
                        308,
                        311,
                        315,
                        319,
                        322,
                        326,
                        329,
                        333,
                        336,
                        340,
                        343,
                        347,
                        351,
                        354,
                        358,
                        362,
                        365,
                        369,
                        373,
                        376,
                        380,
                        383,
                        387,
                        396,
                        407,
                        419,
                        425,
                        431,
                        437,
                        450,
                        458,
                        465,
                        471,
                        477,
                        482,
                        490,
                        497,
                        503,
                        510,
                        519,
                        527,
                        534,
                        540,
                        546,
                        554,
                        562,
                        567,
                        576,
                        584,
                        589,
                        594,
                        601,
                        608,
                        619,
                        637,
                        666,
                        672},
                new int[] {
                        5,
                        119},
                new int[] {
                        5,
                        104},
                new int[] {
                        5,
                        101},
                new int[] {
                        5,
                        114},
                new int[] {
                        5,
                        101},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        501},
                new int[] {
                        5,
                        111},
                new int[] {
                        5,
                        118},
                new int[] {
                        5,
                        101},
                new int[] {
                        5,
                        114},
                new int[] {
                        5,
                        114},
                new int[] {
                        5,
                        105},
                new int[] {
                        5,
                        100},
                new int[] {
                        5,
                        101},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        500},
                new int[] {
                        5,
                        99},
                new int[] {
                        5,
                        111},
                new int[] {
                        5,
                        110},
                new int[] {
                        5,
                        115},
                new int[] {
                        5,
                        116},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        499},
                new int[] {
                        5,
                        97},
                new int[] {
                        5,
                        98},
                new int[] {
                        5,
                        115},
                new int[] {
                        5,
                        116},
                new int[] {
                        5,
                        114},
                new int[] {
                        5,
                        97},
                new int[] {
                        5,
                        99},
                new int[] {
                        5,
                        116},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        498},
                new int[] {
                        5,
                        118},
                new int[] {
                        5,
                        105},
                new int[] {
                        5,
                        114},
                new int[] {
                        5,
                        116},
                new int[] {
                        5,
                        117},
                new int[] {
                        5,
                        97},
                new int[] {
                        5,
                        108},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        497},
                new int[] {
                        5,
                        115},
                new int[] {
                        5,
                        116},
                new int[] {
                        5,
                        97},
                new int[] {
                        5,
                        116},
                new int[] {
                        5,
                        105},
                new int[] {
                        5,
                        99},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        496},
                new int[] {
                        5,
                        105},
                new int[] {
                        5,
                        110},
                new int[] {
                        5,
                        116},
                new int[] {
                        5,
                        101},
                new int[] {
                        5,
                        114},
                new int[] {
                        5,
                        110},
                new int[] {
                        5,
                        97},
                new int[] {
                        5,
                        108},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        495},
                new int[] {
                        5,
                        112},
                new int[] {
                        5,
                        114},
                new int[] {
                        5,
                        111},
                new int[] {
                        5,
                        116},
                new int[] {
                        5,
                        101},
                new int[] {
                        5,
                        99},
                new int[] {
                        5,
                        116},
                new int[] {
                        5,
                        101},
                new int[] {
                        5,
                        100},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        494},
                new int[] {
                        5,
                        112},
                new int[] {
                        5,
                        114},
                new int[] {
                        5,
                        105},
                new int[] {
                        5,
                        118},
                new int[] {
                        5,
                        97},
                new int[] {
                        5,
                        116},
                new int[] {
                        5,
                        101},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        493},
                new int[] {
                        5,
                        112},
                new int[] {
                        5,
                        117},
                new int[] {
                        5,
                        98},
                new int[] {
                        5,
                        108},
                new int[] {
                        5,
                        105},
                new int[] {
                        5,
                        99},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        492},
                new int[] {
                        5,
                        101},
                new int[] {
                        5,
                        118},
                new int[] {
                        5,
                        101},
                new int[] {
                        5,
                        110},
                new int[] {
                        5,
                        116},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        491},
                new int[] {
                        5,
                        115},
                new int[] {
                        5,
                        101},
                new int[] {
                        5,
                        116},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        490},
                new int[] {
                        5,
                        103},
                new int[] {
                        5,
                        101},
                new int[] {
                        5,
                        116},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        489},
                new int[] {
                        5,
                        105},
                new int[] {
                        5,
                        110},
                new int[] {
                        5,
                        116},
                new int[] {
                        5,
                        101},
                new int[] {
                        5,
                        114},
                new int[] {
                        5,
                        102},
                new int[] {
                        5,
                        97},
                new int[] {
                        5,
                        99},
                new int[] {
                        5,
                        101},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        488},
                new int[] {
                        5,
                        115},
                new int[] {
                        5,
                        116},
                new int[] {
                        5,
                        114},
                new int[] {
                        5,
                        117},
                new int[] {
                        5,
                        99},
                new int[] {
                        5,
                        116},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        487},
                new int[] {
                        5,
                        101},
                new int[] {
                        5,
                        110},
                new int[] {
                        5,
                        117},
                new int[] {
                        5,
                        109},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        486},
                new int[] {
                        5,
                        99},
                new int[] {
                        5,
                        108},
                new int[] {
                        5,
                        97},
                new int[] {
                        5,
                        115},
                new int[] {
                        5,
                        115},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        485},
                new int[] {
                        5,
                        112},
                new int[] {
                        5,
                        97},
                new int[] {
                        5,
                        114},
                new int[] {
                        5,
                        116},
                new int[] {
                        5,
                        105},
                new int[] {
                        5,
                        97},
                new int[] {
                        5,
                        108},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        484},
                new int[] {
                        5,
                        118},
                new int[] {
                        5,
                        111},
                new int[] {
                        5,
                        105},
                new int[] {
                        5,
                        100},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        483},
                new int[] {
                        5,
                        97},
                new int[] {
                        5,
                        115},
                new int[] {
                        5,
                        115},
                new int[] {
                        5,
                        101},
                new int[] {
                        5,
                        109},
                new int[] {
                        5,
                        98},
                new int[] {
                        5,
                        108},
                new int[] {
                        5,
                        121},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        482},
                new int[] {
                        5,
                        47},
                new int[] {
                        5,
                        42},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        481},
                new int[] {
                        5,
                        47},
                new int[] {
                        5,
                        47},
                new int[] {
                        2,
                        172,
                        174},
                new int[] {
                        7,
                        10,
                        10,
                        13,
                        13},
                new int[] {
                        2,
                        171},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        480},
                new int[] {
                        5,
                        35},
                new int[] {
                        6,
                        65,
                        90,
                        97,
                        122},
                new int[] {
                        2,
                        177,
                        179},
                new int[] {
                        2,
                        180,
                        182},
                new int[] {
                        6,
                        9,
                        9,
                        32,
                        32},
                new int[] {
                        2,
                        179},
                new int[] {
                        2,
                        183,
                        185},
                new int[] {
                        7,
                        10,
                        10,
                        13,
                        13},
                new int[] {
                        2,
                        182},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        479},
                new int[] {
                        5,
                        58},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        478},
                new int[] {
                        5,
                        118},
                new int[] {
                        5,
                        97},
                new int[] {
                        5,
                        114},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        477},
                new int[] {
                        5,
                        59},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        476},
                new int[] {
                        5,
                        102},
                new int[] {
                        5,
                        105},
                new int[] {
                        5,
                        110},
                new int[] {
                        5,
                        97},
                new int[] {
                        5,
                        108},
                new int[] {
                        5,
                        108},
                new int[] {
                        5,
                        121},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        475},
                new int[] {
                        5,
                        99},
                new int[] {
                        5,
                        97},
                new int[] {
                        5,
                        116},
                new int[] {
                        5,
                        99},
                new int[] {
                        5,
                        104},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        474},
                new int[] {
                        5,
                        116},
                new int[] {
                        5,
                        114},
                new int[] {
                        5,
                        121},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        473},
                new int[] {
                        5,
                        114},
                new int[] {
                        5,
                        101},
                new int[] {
                        5,
                        116},
                new int[] {
                        5,
                        117},
                new int[] {
                        5,
                        114},
                new int[] {
                        5,
                        110},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        472},
                new int[] {
                        5,
                        119},
                new int[] {
                        5,
                        104},
                new int[] {
                        5,
                        105},
                new int[] {
                        5,
                        108},
                new int[] {
                        5,
                        101},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        471},
                new int[] {
                        5,
                        116},
                new int[] {
                        5,
                        104},
                new int[] {
                        5,
                        114},
                new int[] {
                        5,
                        111},
                new int[] {
                        5,
                        119},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        470},
                new int[] {
                        5,
                        102},
                new int[] {
                        5,
                        111},
                new int[] {
                        5,
                        114},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        469},
                new int[] {
                        5,
                        101},
                new int[] {
                        5,
                        108},
                new int[] {
                        5,
                        115},
                new int[] {
                        5,
                        101},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        468},
                new int[] {
                        5,
                        103},
                new int[] {
                        5,
                        111},
                new int[] {
                        5,
                        116},
                new int[] {
                        5,
                        111},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        467},
                new int[] {
                        5,
                        105},
                new int[] {
                        5,
                        102},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        466},
                new int[] {
                        6,
                        9,
                        9,
                        10,
                        10,
                        11,
                        11,
                        12,
                        12,
                        13,
                        13,
                        32,
                        32},
                new int[] {
                        2,
                        262,
                        264},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        465},
                new int[] {
                        5,
                        46},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        462},
                new int[] {
                        5,
                        58},
                new int[] {
                        5,
                        58},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        461},
                new int[] {
                        5,
                        44},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        460},
                new int[] {
                        5,
                        125},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        459},
                new int[] {
                        5,
                        123},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        458},
                new int[] {
                        5,
                        41},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        457},
                new int[] {
                        5,
                        40},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        456},
                new int[] {
                        5,
                        93},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        455},
                new int[] {
                        5,
                        91},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        454},
                new int[] {
                        5,
                        33},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        453},
                new int[] {
                        5,
                        124},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        452},
                new int[] {
                        5,
                        124},
                new int[] {
                        5,
                        61},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        451},
                new int[] {
                        5,
                        124},
                new int[] {
                        5,
                        124},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        450},
                new int[] {
                        5,
                        38},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        449},
                new int[] {
                        5,
                        38},
                new int[] {
                        5,
                        61},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        448},
                new int[] {
                        5,
                        38},
                new int[] {
                        5,
                        38},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        447},
                new int[] {
                        5,
                        37},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        446},
                new int[] {
                        5,
                        37},
                new int[] {
                        5,
                        61},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        445},
                new int[] {
                        5,
                        47},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        444},
                new int[] {
                        5,
                        47},
                new int[] {
                        5,
                        61},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        443},
                new int[] {
                        5,
                        42},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        442},
                new int[] {
                        5,
                        42},
                new int[] {
                        5,
                        61},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        441},
                new int[] {
                        5,
                        45},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        440},
                new int[] {
                        5,
                        45},
                new int[] {
                        5,
                        61},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        439},
                new int[] {
                        5,
                        45},
                new int[] {
                        5,
                        45},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        438},
                new int[] {
                        5,
                        43},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        437},
                new int[] {
                        5,
                        43},
                new int[] {
                        5,
                        61},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        436},
                new int[] {
                        5,
                        43},
                new int[] {
                        5,
                        43},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        435},
                new int[] {
                        5,
                        61},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        434},
                new int[] {
                        5,
                        33},
                new int[] {
                        5,
                        61},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        433},
                new int[] {
                        5,
                        61},
                new int[] {
                        5,
                        61},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        432},
                new int[] {
                        5,
                        62},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        431},
                new int[] {
                        5,
                        62},
                new int[] {
                        5,
                        61},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        430},
                new int[] {
                        5,
                        60},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        429},
                new int[] {
                        5,
                        60},
                new int[] {
                        5,
                        61},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        428},
                new int[] {
                        6,
                        39,
                        39},
                new int[] {
                        2,
                        389,
                        391},
                new int[] {
                        7,
                        39,
                        39},
                new int[] {
                        2,
                        393},
                new int[] {
                        5,
                        92},
                new int[] {
                        4},
                new int[] {
                        6,
                        39,
                        39},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        427},
                new int[] {
                        5,
                        34},
                new int[] {
                        2,
                        398,
                        404},
                new int[] {
                        2,
                        399,
                        401},
                new int[] {
                        7,
                        34,
                        34},
                new int[] {
                        2,
                        403},
                new int[] {
                        5,
                        92},
                new int[] {
                        4},
                new int[] {
                        2,
                        397},
                new int[] {
                        5,
                        34},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        426},
                new int[] {
                        5,
                        64},
                new int[] {
                        5,
                        34},
                new int[] {
                        2,
                        410,
                        416},
                new int[] {
                        2,
                        411,
                        413},
                new int[] {
                        7,
                        34,
                        34},
                new int[] {
                        2,
                        415},
                new int[] {
                        5,
                        34},
                new int[] {
                        5,
                        34},
                new int[] {
                        2,
                        409},
                new int[] {
                        5,
                        34},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        424},
                new int[] {
                        5,
                        98},
                new int[] {
                        5,
                        97},
                new int[] {
                        5,
                        115},
                new int[] {
                        5,
                        101},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        423},
                new int[] {
                        5,
                        116},
                new int[] {
                        5,
                        104},
                new int[] {
                        5,
                        105},
                new int[] {
                        5,
                        115},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        422},
                new int[] {
                        5,
                        110},
                new int[] {
                        5,
                        117},
                new int[] {
                        5,
                        108},
                new int[] {
                        5,
                        108},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        421},
                new int[] {
                        2,
                        438,
                        443},
                new int[] {
                        5,
                        116},
                new int[] {
                        5,
                        114},
                new int[] {
                        5,
                        117},
                new int[] {
                        5,
                        101},
                new int[] {
                        2,
                        448},
                new int[] {
                        5,
                        102},
                new int[] {
                        5,
                        97},
                new int[] {
                        5,
                        108},
                new int[] {
                        5,
                        115},
                new int[] {
                        5,
                        101},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        420},
                new int[] {
                        5,
                        111},
                new int[] {
                        5,
                        98},
                new int[] {
                        5,
                        106},
                new int[] {
                        5,
                        101},
                new int[] {
                        5,
                        99},
                new int[] {
                        5,
                        116},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        419},
                new int[] {
                        5,
                        117},
                new int[] {
                        5,
                        108},
                new int[] {
                        5,
                        111},
                new int[] {
                        5,
                        110},
                new int[] {
                        5,
                        103},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        418},
                new int[] {
                        5,
                        108},
                new int[] {
                        5,
                        111},
                new int[] {
                        5,
                        110},
                new int[] {
                        5,
                        103},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        417},
                new int[] {
                        5,
                        117},
                new int[] {
                        5,
                        105},
                new int[] {
                        5,
                        110},
                new int[] {
                        5,
                        116},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        416},
                new int[] {
                        5,
                        105},
                new int[] {
                        5,
                        110},
                new int[] {
                        5,
                        116},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        415},
                new int[] {
                        5,
                        117},
                new int[] {
                        5,
                        115},
                new int[] {
                        5,
                        104},
                new int[] {
                        5,
                        111},
                new int[] {
                        5,
                        114},
                new int[] {
                        5,
                        116},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        414},
                new int[] {
                        5,
                        115},
                new int[] {
                        5,
                        104},
                new int[] {
                        5,
                        111},
                new int[] {
                        5,
                        114},
                new int[] {
                        5,
                        116},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        413},
                new int[] {
                        5,
                        98},
                new int[] {
                        5,
                        121},
                new int[] {
                        5,
                        116},
                new int[] {
                        5,
                        101},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        412},
                new int[] {
                        5,
                        115},
                new int[] {
                        5,
                        98},
                new int[] {
                        5,
                        121},
                new int[] {
                        5,
                        116},
                new int[] {
                        5,
                        101},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        411},
                new int[] {
                        5,
                        100},
                new int[] {
                        5,
                        101},
                new int[] {
                        5,
                        99},
                new int[] {
                        5,
                        105},
                new int[] {
                        5,
                        109},
                new int[] {
                        5,
                        97},
                new int[] {
                        5,
                        108},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        410},
                new int[] {
                        5,
                        100},
                new int[] {
                        5,
                        111},
                new int[] {
                        5,
                        117},
                new int[] {
                        5,
                        98},
                new int[] {
                        5,
                        108},
                new int[] {
                        5,
                        101},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        409},
                new int[] {
                        5,
                        102},
                new int[] {
                        5,
                        108},
                new int[] {
                        5,
                        111},
                new int[] {
                        5,
                        97},
                new int[] {
                        5,
                        116},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        408},
                new int[] {
                        5,
                        99},
                new int[] {
                        5,
                        104},
                new int[] {
                        5,
                        97},
                new int[] {
                        5,
                        114},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        407},
                new int[] {
                        5,
                        98},
                new int[] {
                        5,
                        111},
                new int[] {
                        5,
                        111},
                new int[] {
                        5,
                        108},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        406},
                new int[] {
                        5,
                        115},
                new int[] {
                        5,
                        116},
                new int[] {
                        5,
                        114},
                new int[] {
                        5,
                        105},
                new int[] {
                        5,
                        110},
                new int[] {
                        5,
                        103},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        405},
                new int[] {
                        5,
                        103},
                new int[] {
                        5,
                        108},
                new int[] {
                        5,
                        111},
                new int[] {
                        5,
                        98},
                new int[] {
                        5,
                        97},
                new int[] {
                        5,
                        108},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        404},
                new int[] {
                        5,
                        110},
                new int[] {
                        5,
                        101},
                new int[] {
                        5,
                        119},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        403},
                new int[] {
                        5,
                        100},
                new int[] {
                        5,
                        101},
                new int[] {
                        5,
                        102},
                new int[] {
                        5,
                        97},
                new int[] {
                        5,
                        117},
                new int[] {
                        5,
                        108},
                new int[] {
                        5,
                        116},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        402},
                new int[] {
                        5,
                        116},
                new int[] {
                        5,
                        121},
                new int[] {
                        5,
                        112},
                new int[] {
                        5,
                        101},
                new int[] {
                        5,
                        111},
                new int[] {
                        5,
                        102},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        401},
                new int[] {
                        5,
                        114},
                new int[] {
                        5,
                        101},
                new int[] {
                        5,
                        102},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        400},
                new int[] {
                        5,
                        111},
                new int[] {
                        5,
                        117},
                new int[] {
                        5,
                        116},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        399},
                new int[] {
                        5,
                        64},
                new int[] {
                        6,
                        65,
                        90,
                        95,
                        95,
                        97,
                        122},
                new int[] {
                        2,
                        597,
                        599},
                new int[] {
                        6,
                        48,
                        57,
                        65,
                        90,
                        95,
                        95,
                        97,
                        122},
                new int[] {
                        2,
                        596},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        398},
                new int[] {
                        5,
                        117},
                new int[] {
                        5,
                        115},
                new int[] {
                        5,
                        105},
                new int[] {
                        5,
                        110},
                new int[] {
                        5,
                        103},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        397},
                new int[] {
                        5,
                        110},
                new int[] {
                        5,
                        97},
                new int[] {
                        5,
                        109},
                new int[] {
                        5,
                        101},
                new int[] {
                        5,
                        115},
                new int[] {
                        5,
                        112},
                new int[] {
                        5,
                        97},
                new int[] {
                        5,
                        99},
                new int[] {
                        5,
                        101},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        396},
                new int[] {
                        2,
                        620,
                        624},
                new int[] {
                        5,
                        48},
                new int[] {
                        5,
                        120},
                new int[] {
                        6,
                        48,
                        57,
                        65,
                        70,
                        97,
                        102},
                new int[] {
                        2,
                        626},
                new int[] {
                        6,
                        48,
                        57},
                new int[] {
                        2,
                        624,
                        626},
                new int[] {
                        2,
                        627,
                        635},
                new int[] {
                        2,
                        628,
                        632},
                new int[] {
                        6,
                        85,
                        85,
                        117,
                        117},
                new int[] {
                        2,
                        630,
                        631},
                new int[] {
                        6,
                        76,
                        76,
                        108,
                        108},
                new int[] {
                        2,
                        635},
                new int[] {
                        6,
                        76,
                        76,
                        108,
                        108},
                new int[] {
                        2,
                        634,
                        635},
                new int[] {
                        6,
                        85,
                        85,
                        117,
                        117},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        463},
                new int[] {
                        2,
                        638,
                        653},
                new int[] {
                        6,
                        48,
                        57},
                new int[] {
                        2,
                        638,
                        640},
                new int[] {
                        2,
                        641,
                        644},
                new int[] {
                        5,
                        46},
                new int[] {
                        6,
                        48,
                        57},
                new int[] {
                        2,
                        642,
                        644},
                new int[] {
                        2,
                        645,
                        650},
                new int[] {
                        6,
                        69,
                        69,
                        101,
                        101},
                new int[] {
                        2,
                        647,
                        648},
                new int[] {
                        6,
                        43,
                        43,
                        45,
                        45},
                new int[] {
                        6,
                        48,
                        57},
                new int[] {
                        2,
                        648,
                        650},
                new int[] {
                        2,
                        651,
                        652},
                new int[] {
                        6,
                        68,
                        68,
                        70,
                        70,
                        77,
                        77,
                        100,
                        100,
                        102,
                        102,
                        109,
                        109},
                new int[] {
                        2,
                        664},
                new int[] {
                        5,
                        46},
                new int[] {
                        6,
                        48,
                        57},
                new int[] {
                        2,
                        654,
                        656},
                new int[] {
                        2,
                        657,
                        662},
                new int[] {
                        6,
                        69,
                        69,
                        101,
                        101},
                new int[] {
                        2,
                        659,
                        660},
                new int[] {
                        6,
                        43,
                        43,
                        45,
                        45},
                new int[] {
                        6,
                        48,
                        57},
                new int[] {
                        2,
                        660,
                        662},
                new int[] {
                        2,
                        663,
                        664},
                new int[] {
                        6,
                        68,
                        68,
                        70,
                        70,
                        77,
                        77,
                        100,
                        100,
                        102,
                        102,
                        109,
                        109},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        464},
                new int[] {
                        6,
                        65,
                        90,
                        95,
                        95,
                        97,
                        122},
                new int[] {
                        2,
                        668,
                        670},
                new int[] {
                        6,
                        48,
                        57,
                        65,
                        90,
                        95,
                        95,
                        97,
                        122},
                new int[] {
                        2,
                        667},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        425},
                new int[] {
                        4},
                new int[] {
                        10,
                        1},
                new int[] {
                        1,
                        -1}};
        internal static string[] BlockEnds = new string[] {
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                "*/",
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null};
        internal static int[] NodeFlags = new int[] {
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0};
        public SlangTokenizer(IEnumerable<char> input) : 
                base(SlangTokenizer.Program, SlangTokenizer.BlockEnds, SlangTokenizer.NodeFlags, input) {
        }
        public const int namespaceKeyword = 396;
        public const int usingKeyword = 397;
        public const int verbatimIdentifier = 398;
        public const int outKeyword = 399;
        public const int refKeyword = 400;
        public const int typeOf = 401;
        public const int defaultOf = 402;
        public const int newKeyword = 403;
        public const int globalKeyword = 404;
        public const int stringType = 405;
        public const int boolType = 406;
        public const int charType = 407;
        public const int floatType = 408;
        public const int doubleType = 409;
        public const int decimalType = 410;
        public const int sbyteType = 411;
        public const int byteType = 412;
        public const int shortType = 413;
        public const int ushortType = 414;
        public const int intType = 415;
        public const int uintType = 416;
        public const int longType = 417;
        public const int ulongType = 418;
        public const int objectType = 419;
        public const int boolLiteral = 420;
        public const int nullLiteral = 421;
        public const int thisRef = 422;
        public const int baseRef = 423;
        public const int verbatimStringLiteral = 424;
        public const int identifier = 425;
        public const int stringLiteral = 426;
        public const int characterLiteral = 427;
        public const int lte = 428;
        public const int lt = 429;
        public const int gte = 430;
        public const int gt = 431;
        public const int eqEq = 432;
        public const int notEq = 433;
        public const int eq = 434;
        public const int inc = 435;
        public const int addAssign = 436;
        public const int add = 437;
        public const int dec = 438;
        public const int subAssign = 439;
        public const int sub = 440;
        public const int mulAssign = 441;
        public const int mul = 442;
        public const int divAssign = 443;
        public const int div = 444;
        public const int modAssign = 445;
        public const int mod = 446;
        public const int and = 447;
        public const int bitwiseAndAssign = 448;
        public const int bitwiseAnd = 449;
        public const int or = 450;
        public const int bitwiseOrAssign = 451;
        public const int bitwiseOr = 452;
        public const int not = 453;
        public const int lbracket = 454;
        public const int rbracket = 455;
        public const int lparen = 456;
        public const int rparen = 457;
        public const int lbrace = 458;
        public const int rbrace = 459;
        public const int comma = 460;
        public const int colonColon = 461;
        public const int dot = 462;
        public const int integerLiteral = 463;
        public const int floatLiteral = 464;
        public const int whitespace = 465;
        public const int ifKeyword = 466;
        public const int gotoKeyword = 467;
        public const int elseKeyword = 468;
        public const int forKeyword = 469;
        public const int throwKeyword = 470;
        public const int whileKeyword = 471;
        public const int returnKeyword = 472;
        public const int tryKeyword = 473;
        public const int catchKeyword = 474;
        public const int finallyKeyword = 475;
        public const int semi = 476;
        public const int varType = 477;
        public const int colon = 478;
        public const int directive = 479;
        public const int lineComment = 480;
        public const int blockComment = 481;
        public const int assemblyKeyword = 482;
        public const int voidType = 483;
        public const int partialKeyword = 484;
        public const int classKeyword = 485;
        public const int enumKeyword = 486;
        public const int structKeyword = 487;
        public const int interfaceKeyword = 488;
        public const int getKeyword = 489;
        public const int setKeyword = 490;
        public const int eventKeyword = 491;
        public const int publicKeyword = 492;
        public const int privateKeyword = 493;
        public const int protectedKeyword = 494;
        public const int internalKeyword = 495;
        public const int staticKeyword = 496;
        public const int virtualKeyword = 497;
        public const int abstractKeyword = 498;
        public const int constKeyword = 499;
        public const int overrideKeyword = 500;
        public const int whereKeyword = 501;
    }
}
